services:
  web:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app:cached
      - bundle_path:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development

volumes:
  bundle_path:
